ALTER TABLE `User`
  MODIFY `role` ENUM('ADMIN', 'SCHOOL_ADMIN', 'FINANCE', 'ACCOUNTING', 'GROUP_LEADER', 'VIEWER', 'MEMBER') NOT NULL,
  ADD COLUMN `memberId` VARCHAR(191) NULL;

CREATE UNIQUE INDEX `User_memberId_key` ON `User`(`memberId`);

ALTER TABLE `User`
  ADD CONSTRAINT `User_memberId_fkey`
  FOREIGN KEY (`memberId`) REFERENCES `Member`(`id`)
  ON DELETE SET NULL ON UPDATE CASCADE;
